language: node_js
node_js:
  - "10"
  - "8"

services:
  - mongodb
addons:
  chrome: stable
before_script:
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov npm test
cache:
  directories:
    - "node_modules"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coveralls
notifications:
  email: false
